### ISSUE TITLE
where is Dll1.lib, bro?

### ISSUE THREAD

**Issue by Buen16** [si1kyyy/CrossFireCheat#2]
lack of Dll1.lib

**Comment by Buen16** [comment]
by the way, are these offsets still valid?

**Comment by Buen16** [comment]
偏移似乎有问题，例如gbPlayerBase附近的内存我读取的时候发现并未分配，全是0

**Comment by Buen16** [comment]
兄弟，你这些偏移是不是都是旧版的啊，都没用了好像

**Comment by si1kyyy** [comment]
> lack of Dll1.lib

这是我自己的读写驱动lib库，你可以选择去市场购买一个读写驱动或是自己开发一款驱动，可以参考我的ReadWrite项目

**Comment by si1kyyy** [comment]
> 兄弟，你这些偏移是不是都是旧版的啊，都没用了好像
我这上传日期都是多久之前的了，偏移你去加几个CF易语言的群就有了

**Comment by Buen16** [comment]
好的谢谢，已解决
